### ISSUE TITLE
Cant't build on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by AokiAhishatsu** [GrimKriegor/TES3MP-deploy#23]
I'm getting:
`>> Checking if the compiler has the necessary features
./tes3mp-deploy.sh: 334: ./tes3mp-deploy.sh: arithmetic expression: expecting primary: "7*(10**(5-1))"
`

`gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)`

**Comment by GrimKriegor** [comment]
Hello there. How are you executing the script?

**Comment by AokiAhishatsu** [comment]
I tried:
`sh ./tes3mp-deploy.sh -i`
and
`sudo sh ./tes3mp-deploy.sh -i`

**EDIT:**
`bash ./tes3mp-deploy.sh -i` works

I used `sh` because `./tes3mp-deploy.sh` gave me:
`bash: ./tes3mp-deploy.sh: Permission denied`

Ubuntu brain cancer...

**Comment by GrimKriegor** [comment]
Glad you were able to find the problem by yourself.

Indeed, the problem was that you were using the wrong interpreter, this script is a bash script, as you can see in its first line and will fail when ran with the sh shell.

https://github.com/GrimKriegor/TES3MP-deploy/blob/master/tes3mp-deploy.sh#L1

Anyway, nowadays this script is meant to be used on package automation only, I suggest that you use the pre-build packages available in the releases page.

https://github.com/TES3MP/openmw-tes3mp/releases

Best of luck!
