### ISSUE TITLE
Change [Modules] to [Plugins]

### ISSUE THREAD

**Issue by testman42** [GrimKriegor/TES3MP-deploy#27]
Server executable says that it doesn't find "plugins" when built with current TES3MP-deploy.
[settings file](https://github.com/TES3MP/openmw-tes3mp/blob/2e227c7af5a75574451c5c1dee49ead7179561f4/files/tes3mp/tes3mp-server-default.cfg#L11) seems to have [Plugins] section for LUA stuff now.

After I copied the 
```
[Plugins]
home = ~/local/openmw/tes3mp
plugins = serverCore.lua
```

part into the settings fine (with correct path to CoreScripts) the issue was resolved.

**Comment by GrimKriegor** [comment]
Indeed, this has been an issue for people building their own clients since TES3MP `0.7.0` and `master` started using incompatible configuration files.

Should now be fixed on a clean install.
https://github.com/GrimKriegor/TES3MP-deploy/commit/0dd296e044cc36826225329c2927c9c45edbcad3
https://github.com/GrimKriegor/TES3MP-deploy/commit/68c80f6c0964e84a001bf661f5bf495a38295efb
